apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edge-sip2.fullname" . }}
  labels:
    {{- include "edge-sip2.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "edge-sip2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "edge-sip2.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "edge-sip2.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          volumeMounts:
          - mountPath: /usr/verticles/sip2.conf
            name: sip2
            subPath: sip2.conf
          - mountPath: /usr/verticles/sip2-tenants.conf
            name: sip2-tenants
            subPath: sip2-tenants.conf
          args:
            - -conf
            - sip2.conf
          env:
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: DB_DATABASE
                  name: db-connect-modules
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: DB_HOST
                  name: db-connect-modules
            - name: DB_MAXPOOLSIZE
              value: {{ .Values.dbMaxPoolSize | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: db-connect-modules
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: DB_PORT
                  name: db-connect-modules
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME
                  name: db-connect-modules
            - name: ENV
              valueFrom:
                secretKeyRef:
                  key: ENV
                  name: db-connect-modules
            - name: JAVA_OPTIONS
              value: {{ .Values.javaOptions | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: sip2
        secret:
          secretName: sip2.conf
      - name: sip2-tenants
        secret:
          secretName: sip2-tenants.conf
      - name: edge-ephemeral
        secret:
          secretName: edge-sip2-ephemeral.properties
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
