apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-connexion.fullname" . }}
  labels:
    {{- include "edge-connexion.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.hostPort }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: http-connextion
  selector:
    {{- include "edge-connexion.selectorLabels" . | nindent 4 }}
