apiVersion: v1
kind: Service
metadata:
  name: {{ include "mod-z3950.fullname" . }}
  labels:
    {{- include "mod-z3950.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.zserver.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: z3950
    - port: {{ .Values.sru.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "mod-z3950.selectorLabels" . | nindent 4 }}
